# Generated by Django 5.2.3 on 2025-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_skillcategory_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text='e.g. devicon-python-plain', max_length=100),
        ),
    ]
