# Generated by Django 5.2.3 on 2025-06-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_skill_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_image',
            field=models.CharField(blank=True, help_text='devicon-plain', max_length=100),
        ),
    ]
