# Generated by Django 5.2.3 on 2025-06-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_skill_icon_class_skill_icon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_image',
        ),
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
