# Generated by Django 5.2.3 on 2025-06-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_project_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='address',
            new_name='location',
        ),
    ]
