# Generated by Django 5.0 on 2025-07-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
