# Generated by Django 5.0 on 2025-07-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='main_courses',
            field=models.TextField(blank=True, help_text='Enter courses separated by new lines'),
        ),
    ]
